/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.88
 * Generated at: 2024-05-20 00:43:55 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class about_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(2);
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1714458788072L));
    _jspx_dependants.put("jar:file:/C:/data/jsp/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/ex13/WEB-INF/lib/jstl-1.2.jar!/META-INF/fmt.tld", Long.valueOf(1153352682000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.LinkedHashSet<>(3);
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("    \r\n");
      out.write("<style>\r\n");
      out.write("	.bi-suit-heart, .bi-suit-heart-fill{\r\n");
      out.write("		color: red;\r\n");
      out.write("		float: right;\r\n");
      out.write("		font-size:20px;\r\n");
      out.write("		cursor:pointer;\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write("</style>    \r\n");
      out.write("<div class=\"my-5\">\r\n");
      out.write("	<div class=\"row\">\r\n");
      out.write("		<div class=\"col-4\">\r\n");
      out.write("			<div class=\"mb-5\">\r\n");
      out.write("				<form name=\"frm\">\r\n");
      out.write("				<div class=\"input-group\">\r\n");
      out.write("					<input placeholder=\"검색어\" class=\"form-control\" name=\"word\">\r\n");
      out.write("					<button class=\"btn btn-success\">검색</button>\r\n");
      out.write("				</div>\r\n");
      out.write("				</form>\r\n");
      out.write("			</div>\r\n");
      out.write("			<img src=\"/image/ad03.png\" width=\"100%\">\r\n");
      out.write("		</div>\r\n");
      out.write("		<div class=\"col-8\">\r\n");
      out.write("			<div class=\"alert alert-primary text-center\">\r\n");
      out.write("				<h4>지금 떠오르는 위스키</h4>\r\n");
      out.write("			</div>\r\n");
      out.write("			<div id=\"div_shop\" class=\"row\"></div>\r\n");
      out.write("			<div id=\"pagination\" class=\"pagination justify-content-center\"></div>\r\n");
      out.write("		</div>\r\n");
      out.write("	</div>\r\n");
      out.write("		<div class=\"alert alert-success text-center\">\r\n");
      out.write("			<h5>이번주 주말 추천 전통주</h5>\r\n");
      out.write("		</div>\r\n");
      out.write("	<div id=\"div_bed\" class=\"row\"></div>\r\n");
      out.write("	<div id=\"pagination2\" class=\"pagination justify-content-center\"></div>\r\n");
      out.write("</div>\r\n");
      out.write("<script id=\"temp_shop\" type=\"x=handlebars-template\">\r\n");
      out.write("	{{#each .}}\r\n");
      out.write("		<div class=\"col-4\">\r\n");
      out.write("			<div class=\"mb-2\">\r\n");
      out.write("				<img gid=\"{{gid}}\" src=\"{{image}}\" width=\"95%\" style=\"cursor:pointer;\">\r\n");
      out.write("			</div>\r\n");
      out.write("			<div>{{brand}}</div>\r\n");
      out.write("			<div class=\"ellipsis\">{{{title}}}</div>\r\n");
      out.write("			<div class=\"mb-2 text-center\">\r\n");
      out.write("				{{fmtPrice price}}\r\n");
      out.write("				<span class=\"bi {{heart ucnt}}\" gid=\"{{gid}}\">\r\n");
      out.write("					<span style=\"font-size:12px;color:red;\">{{fcnt}}</span>\r\n");
      out.write("				</span>\r\n");
      out.write("				<span style=\"color=:blace; float:right;\">\r\n");
      out.write("					<i class=\"bi bi-sticky\" style=\"font-size:20px\"></i>\r\n");
      out.write("					<span style=\"font-size:12px;color:black;\" class=\"me-1\">{{rcnt}}</span>\r\n");
      out.write("				</span>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	{{/each}}\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("<script id=\"temp_bed\" type=\"x=handlebars-template\">\r\n");
      out.write("	{{#each .}}\r\n");
      out.write("		<div class=\"col-2 col-md-4 col-lg-2 mb-5\">\r\n");
      out.write("			<div class=\"mb-2\">\r\n");
      out.write("				<img gid=\"{{gid}}\" src=\"{{image}}\" width=\"95%\" style=\"cursor:pointer;\">\r\n");
      out.write("			</div>\r\n");
      out.write("			<div>{{brand}}</div>\r\n");
      out.write("			<div class=\"ellipsis\">{{{title}}}</div>\r\n");
      out.write("			<div class=\"mb-2\">\r\n");
      out.write("				{{fmtPrice price}}\r\n");
      out.write("				<span class=\"bi {{heart ucnt}}\" gid=\"{{gid}}\">\r\n");
      out.write("					<span style=\"font-size:12px;color:red;\">{{fcnt}}</span>\r\n");
      out.write("				</span>\r\n");
      out.write("				<span style=\"color=:blace; float:right;\">\r\n");
      out.write("					<i class=\"bi bi-sticky\" style=\"font-size:20px\"></i>\r\n");
      out.write("					<span style=\"font-size:12px;color:black;\" class=\"me-1\">{{rcnt}}</span>\r\n");
      out.write("				</span>\r\n");
      out.write("			</div>\r\n");
      out.write("		</div>\r\n");
      out.write("	{{/each}}\r\n");
      out.write("</script>\r\n");
      out.write("<script>\r\n");
      out.write("	Handlebars.registerHelper(\"fmtPrice\",function(price){\r\n");
      out.write("		return price.toString().replace(/\\B(?=(\\d{3})+(?!\\d))/g, \",\")\r\n");
      out.write("	})\r\n");
      out.write("	\r\n");
      out.write("	Handlebars.registerHelper(\"heart\",function(value){\r\n");
      out.write("		if(value==0) return \"bi-suit-heart\";\r\n");
      out.write("		else return \"bi-suit-heart-fill\";\r\n");
      out.write("	})\r\n");
      out.write("</script>\r\n");
      out.write("<script>\r\n");
      out.write("	let size=10;\r\n");
      out.write("	let page= 1;\r\n");
      out.write("	let word=\"\";\r\n");
      out.write("	//이미지를 클릭한 경우\r\n");
      out.write("	$(\"#div_shop\").on(\"click\", \"img\" ,function(){\r\n");
      out.write("		const gid=$(this).attr(\"gid\");\r\n");
      out.write("		location.href=\"/goods/read?gid=\"+gid;\r\n");
      out.write("	})\r\n");
      out.write("	$(\"#div_bed\").on(\"click\", \"img\" ,function(){\r\n");
      out.write("	const gid=$(this).attr(\"gid\");\r\n");
      out.write("	location.href=\"/goods/read?gid=\"+gid;\r\n");
      out.write("	})\r\n");
      out.write("	\r\n");
      out.write("	//빈 하트를 클릭한 경우\r\n");
      out.write("	$(\"#div_shop\").on(\"click\",\".bi-suit-heart\",function(){\r\n");
      out.write("		if(uid){\r\n");
      out.write("			const gid=$(this).attr(\"gid\");\r\n");
      out.write("			//alert(uid+\":\"+gid);\r\n");
      out.write("			$.ajax({\r\n");
      out.write("				type:\"post\",\r\n");
      out.write("				url:\"/favorite/insert\",\r\n");
      out.write("				data:{uid,gid},\r\n");
      out.write("				success:function(){\r\n");
      out.write("					alert(\"좋아요! 등록\");\r\n");
      out.write("					getData();\r\n");
      out.write("				}\r\n");
      out.write("			})\r\n");
      out.write("		}else{\r\n");
      out.write("			location.href=\"/user/login\";\r\n");
      out.write("		}\r\n");
      out.write("	});\r\n");
      out.write("	$(\"#div_bed\").on(\"click\",\".bi-suit-heart\",function(){\r\n");
      out.write("		if(uid){\r\n");
      out.write("			const gid=$(this).attr(\"gid\");\r\n");
      out.write("			//alert(uid+\":\"+gid);\r\n");
      out.write("			$.ajax({\r\n");
      out.write("				type:\"post\",\r\n");
      out.write("				url:\"/favorite/insert\",\r\n");
      out.write("				data:{uid,gid},\r\n");
      out.write("				success:function(){\r\n");
      out.write("					alert(\"좋아요! 등록\");\r\n");
      out.write("					getDataBed();\r\n");
      out.write("				}\r\n");
      out.write("			})\r\n");
      out.write("		}else{\r\n");
      out.write("			location.href=\"/user/login\";\r\n");
      out.write("		}\r\n");
      out.write("	});\r\n");
      out.write("\r\n");
      out.write("	//채워진 하트를 클릭한 경우\r\n");
      out.write("	$(\"#div_bed\").on(\"click\",\".bi-suit-heart-fill\",function(){\r\n");
      out.write("		const gid=$(this).attr(\"gid\");\r\n");
      out.write("		//alert(uid+\":\"+gid);\r\n");
      out.write("		$.ajax({\r\n");
      out.write("			type:\"post\",\r\n");
      out.write("			url:\"/favorite/delete\",\r\n");
      out.write("			data:{uid,gid},\r\n");
      out.write("			success:function(){\r\n");
      out.write("				alert(\"좋아요! 취소\");\r\n");
      out.write("				getDataBed();\r\n");
      out.write("			}\r\n");
      out.write("		})\r\n");
      out.write("	});\r\n");
      out.write("	$(\"#div_shop\").on(\"click\",\".bi-suit-heart-fill\",function(){\r\n");
      out.write("		const gid=$(this).attr(\"gid\");\r\n");
      out.write("		//alert(uid+\":\"+gid);\r\n");
      out.write("		$.ajax({\r\n");
      out.write("			type:\"post\",\r\n");
      out.write("			url:\"/favorite/delete\",\r\n");
      out.write("			data:{uid,gid},\r\n");
      out.write("			success:function(){\r\n");
      out.write("				alert(\"좋아요! 취소\");\r\n");
      out.write("				getData();\r\n");
      out.write("			}\r\n");
      out.write("		})\r\n");
      out.write("	});\r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write("	$(frm).on(\"submit\",function(e){\r\n");
      out.write("		e.preventDefault();\r\n");
      out.write("		word=$(frm.word).val();\r\n");
      out.write("		page=1;\r\n");
      out.write("		getTotal();\r\n");
      out.write("	})\r\n");
      out.write("	\r\n");
      out.write("	getTotal();\r\n");
      out.write("	function getData(){\r\n");
      out.write("		let size=6;\r\n");
      out.write("		let page=1;\r\n");
      out.write("		let word=\"위스키\";\r\n");
      out.write("		$.ajax({\r\n");
      out.write("			type:\"get\",\r\n");
      out.write("			url:\"/goods/list.json\",\r\n");
      out.write("			dataType:\"json\",\r\n");
      out.write("			data:{word,size,page,uid},\r\n");
      out.write("			success:function(data){\r\n");
      out.write("				const temp=Handlebars.compile($(\"#temp_shop\").html());\r\n");
      out.write("				$(\"#div_shop\").html(temp(data));\r\n");
      out.write("			}\r\n");
      out.write("		})\r\n");
      out.write("	}\r\n");
      out.write("	getDataBed();\r\n");
      out.write("	function getDataBed(){\r\n");
      out.write("		let size=12;\r\n");
      out.write("		let page= 1;\r\n");
      out.write("		let word=\"\";\r\n");
      out.write("		$.ajax({\r\n");
      out.write("			type:\"get\",\r\n");
      out.write("			url:\"/goods/list.json\",\r\n");
      out.write("			dataType:\"json\",\r\n");
      out.write("			data:{word,size,page,uid},\r\n");
      out.write("			success:function(data){\r\n");
      out.write("				const temp=Handlebars.compile($(\"#temp_bed\").html());\r\n");
      out.write("				$(\"#div_bed\").html(temp(data));\r\n");
      out.write("			}\r\n");
      out.write("		})\r\n");
      out.write("	}\r\n");
      out.write("	function getTotal(){\r\n");
      out.write("		$.ajax({\r\n");
      out.write("			type:\"get\",\r\n");
      out.write("			url:\"/goods/total\",\r\n");
      out.write("			data:{word},\r\n");
      out.write("			success:function(data){\r\n");
      out.write("				const total= parseInt(data);\r\n");
      out.write("				if(total==0){\r\n");
      out.write("					alert(\"검색 내용이 없습니다!\");\r\n");
      out.write("					$(frm.word).val(\"\");\r\n");
      out.write("					return;\r\n");
      out.write("				}\r\n");
      out.write("				const totalPage=Math.ceil(data/size);\r\n");
      out.write("				$(\"#pagination\").twbsPagination(\"changeTotalPages\", totalPage, page);\r\n");
      out.write("				if(total>size){\r\n");
      out.write("					$(\"#pagination\").show();\r\n");
      out.write("				}else{\r\n");
      out.write("					$(\"#pagination\").hide();\r\n");
      out.write("				}\r\n");
      out.write("				$(\"#total\").html(\"검색수: \" + total);\r\n");
      out.write("			}\r\n");
      out.write("		})\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	$('#pagination').twbsPagination({\r\n");
      out.write("	      totalPages:10, \r\n");
      out.write("	      visiblePages: 1, \r\n");
      out.write("	      startPage : 1,\r\n");
      out.write("	      initiateStartPageClick: false, \r\n");
      out.write("	      first:'<i class=\"bi bi-chevron-double-left text-dark\"></i>', \r\n");
      out.write("	      prev :'<i class=\"bi bi-chevron-left text-dark\"></i>',\r\n");
      out.write("	      next :'<i class=\"bi bi-chevron-right text-dark\"></i>',\r\n");
      out.write("	      last :'<i class=\"bi bi-chevron-double-right text-dark\"></i>',\r\n");
      out.write("	      onPageClick: function (event, clickPage) {\r\n");
      out.write("	          page=clickPage; \r\n");
      out.write("	          getData();\r\n");
      out.write("	      }\r\n");
      out.write("	   });\r\n");
      out.write("</script>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
